### ISSUE TITLE
vanity import broken

### ISSUE THREAD

**Issue by acim** [leighmcculloch/gochecknoglobals#20]
```
package 4d63.com/gochecknoglobals/checknoglobals: unrecognized import path "4d63.com/gochecknoglobals/checknoglobals": reading https://4d63.com/gochecknoglobals/checknoglobals?go-get=1: 404 Not Found
```

**Comment by leighmcculloch** [comment]
👀

**Comment by leighmcculloch** [comment]
Thanks for reporting this, this has been fixed in https://github.com/leighmcculloch/4d63.com/commit/069cf05efae9c2f341b3587d7bd2789a72701841 and deployed. The issue was the subpackage was not being served. Importing worked most of the time because of GOPROXY caches, but whenever pulling directly it would have failed.
