### ISSUE TITLE
Feature Request: Add check for Exported global variables

### ISSUE THREAD

**Issue by s3rj1k** [leighmcculloch/gochecknoglobals#7]
Would be nice to see an option to detect only exported global variables.

**Comment by leighmcculloch** [comment]
👋 @s3rj1k could you provide an example of where you've found this would have been useful?

**Comment by s3rj1k** [comment]
@leonklingele Hi, yes.

For example when you have shared linters config for all of your projects and you use it for applications and packages.

So with this option linter will warn me only that globaly exported variable is present inside package.

Sometimes you just have to use global variables.

**Comment by leighmcculloch** [comment]
Thanks for providing some more context. The goal of `gochecknoglobals` is to create as side-effect code as possible, and global variables, especially hidden unexported global variables inside packages, can cause side effects. The caller makes calls to functions and their behavior changes over time because state is stored inside global variables. A goal of this tool is to stay as least configurable as possible. If you don't want to run it on a specific file I suggest explicitly not running it on files you want to allow global variables.

There are some cases that we do need globals, for things like constants that can't be stored in a `const` like slices. If you have some specific cases that makes sense allowing in all cases to marked as a global, can you open an issue proposing that?

**Comment by s3rj1k** [comment]
for case of whitelisting one can use `//nolint` option when using gochecknoglobals inside some linter wrapper like gometalinter
point was to add a bit of conformability, exceptions can be handled
